#%RAML 1.0
title: dge API - Course Reserves LTI Tool
baseUri: https://github.com/folio-org/edge-lti-courses
version: v1

documentation:
  - title: dge API - Course Reserves LTI Tool
    content: Edge API to allow LTI platforms to fetch course reserves

/lti-courses:
  /deep-link-request:
    displayName: LTI Deep Link Request handler
    post:
      description: LtiDeepLinkResponse containing html deep links
      responses:
        200:
          description: "Success"
          body:
            application/hmtl:
      queryParameters:
        apikey:
          description: "API Key"
          type: string
  /reserves:
    /{courseId}:
      displayName: Course item reserves by Folio course ID
      uriParameters:
        courseId:
          description: The UUID of a Folio course listing in mod-courses
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      get:
        description: Return item reserves for the specified FOLIO course id
        responses:
          200:
            description: "Success"
            body:
              application/json:
/admin/health:
  displayName: Health Check
  get:
    description: Health Check
    responses:
      200:
        description: "Success"
        body:
          text/plain:
